version: "3.7"

services:
  app:
    build:
      args:
        user: dapostolatos
        uid: 1000
      context: ./app
      dockerfile: Dockerfile
    image: leads
    container_name: leads-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    networks:
      - leads

  nginx:
    image: nginx:alpine
    container_name: leads-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - leads

networks:
  leads:
    driver: bridge