version: "3.7"

services:
  app:
    build:
      args:
        user: dapostolatos
        uid: 1000
      context: ./app
      dockerfile: Dockerfile
    image: leads
    container_name: leads-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    networks:
      - leads

  mongo:
    image: mongo:latest
    container_name: leads-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: leads
    ports:
      - 27017:27017
    volumes: 
      - /data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - leads

  nginx:
    image: nginx:alpine
    container_name: leads-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - leads

networks:
  leads:
    driver: bridge